---
title: "Figure2.Functional Capacity of Microbial Communities"
author: "LYM"
date: "2025-01-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###a.pheatmap of function
```{r pheatmap}
library(pheatmap)
#write.table(BQ115_CRSwNP40_CRSwNP50_merged_df_CT21_mean_Pathway3_ko1_unique2_cleaned,"D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Rdata//CON_CT1_CT2_mean_Pathway3_pheatmap20250113.txt",sep="\t",quote=F)
#write.table(row_annotation,"D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Rdata//CON_CT1_CT2_mean_Pathway3_row_annotation.txt",sep="\t",quote=F)

CON_CT1_CT2_mean_Pathway3_pheatmap<-read.table("D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Rdata//CON_CT1_CT2_mean_Pathway3_pheatmap20250113.txt", header = T, sep = "\t")
CON_CT1_CT2_mean_Pathway3_row_annotation<-read.table("D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Rdata//CON_CT1_CT2_mean_Pathway3_row_annotation.txt", header = T, sep = "\t")


pdf("D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Figure//Figure2A_pheatmap_group_pathway_2.pdf",width=8,height=10)
pheatmap(log(CON_CT1_CT2_mean_Pathway3_pheatmap+0.00001),annotation_row = CON_CT1_CT2_mean_Pathway3_row_annotation,show_rownames = FALSE,color = custom_colors,scale="row")
dev.off()
```

###b.Number of KEGG
```{r boxplot}
#write.table(KEGG_no,"D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Rdata//CON_CT1_CT2_mean_Pathway3_number.txt",sep="\t",quote=F)
KEGG_no<-read.table("D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Rdata//CON_CT1_CT2_mean_Pathway3_number.txt",sep="\t",header=T)
KEGG_no$Group<-factor(KEGG_no$Group,levels=c("CON",'CT1','CT2'))
pdf("D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Figure//Figure2B_CON_CT1_CT2_KEGG_no.pdf", width=4,height=4)
ggplot(data=KEGG_no,aes(x=Group,y=Number_KEGG))+
  geom_boxplot(aes(fill=Group),outlier.colour=NA)+
  scale_fill_manual(values=c("CON"="#E9CF91",'CT1'="#F28E97",'CT2'="#8FA9FC"),labels=c("CON",'CT1','CT2'))+
  theme_classic()+
  labs(x=paste("Group"),y=paste("Number of observed KEGG(L3)"))+
  theme(axis.text.x=element_text(size=10,colour="#000000"), 
        axis.text.y=element_text(size=10,colour="#000000"),
        axis.title.x=element_text(size=10,colour="#000000"),
        axis.title.y=element_text(size=10,colour="#000000"),
        legend.text=element_text(size=10))+
  geom_jitter(position=position_jitter(0.08))+
  geom_signif(comparisons=list(c("CON","CT1"),c('CT1','CT2'),c("CON","CT2")),
              test=wilcox.test,step_increase=0.1, 
              map_signif_level=function(p)sprintf("p = %.2g", p), 
              colour="#000000")
dev.off()
```

###c.mean abundance of KEGG
```{r mean abundance}

###R做STAMP分析

library(tidyverse)

save(BQ115_CRSwNP40_CRSwNP50_merged_df2_Train_genus_filter,
     BQ115_CRSwNP40_CRSwNP50_merged_df2_Train,
     file="D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Rdata//Figure2C_mean_abundanceofKEGG.Rdata")
load("D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Rdata//Figure2C_mean_abundanceofKEGG.Rdata")
BQ115_CRSwNP40_CRSwNP50_merged_df2_Train_genus_filter1 <- BQ115_CRSwNP40_CRSwNP50_merged_df2_Train_genus_filter %>% filter(apply(BQ115_CRSwNP40_CRSwNP50_merged_df2_Train_genus_filter,1,mean) > 1)

dim(BQ115_CRSwNP40_CRSwNP50_merged_df2_Train_genus_filter1)
data<- BQ115_CRSwNP40_CRSwNP50_merged_df2_Train

write.table(BQ115_CRSwNP40_CRSwNP50_merged_df2_Train,"D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//BQ115_CRSwNP40_CRSwNP50_merged_df2_Train20250113.txt",sep="\t",quote=F)
write.table(BQ115_CRSwNP40_CRSwNP50_merged_df2_Train,"D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//CT1_CT2_Pathway_Train_20250113.txt",sep="\t",quote=F)
write.table(BQ115_CRSwNP40_CRSwNP50_merged_df2_Train_genus_filter1,"D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//CT1_CT2_Pathway_Train_filter_20250113.txt",sep="\t",quote=F)


##T-test 首先对数据进行调整，构建用于t-test的数据框。

data <- t(data)
data1 <- merge(BQ72_BQ40_BQ50_communityType_Group2,data,by.x=0,by.y=0)
#colnames(data1) <- c(colnames(data),"Group")
data1$CommunityType <- as.factor(data1$CommunityType)

#首先使用select_if选择格式为数字列，然后使用map_df分别对每一个列进行t-test，最后使用broom：tidy将结果整合在tidy的数据框中。
diff <- data1 %>%
    select_if(is.numeric) %>%
    map_df(~ broom::tidy(t.test(. ~ CommunityType,data = data1)), .id = 'var')

##最后对t-test的p值进行校正，保留校正后p值小于0.05的数据。
diff$p.value <- p.adjust(diff$p.value,"bonferroni")
diff <- diff %>% filter(p.value < 0.05)

##秩和检验,秩和检验和上面的t-test一样，只需要把代码中的t.test换成wilcox.test就可以了。

diff1_wilcox <- data1 %>%
    select_if(is.numeric) %>%
    map_df(~ broom::tidy(wilcox.test(. ~ CommunityType,data = data1)), .id = 'var')
 
diff1_wilcox$p.value <- p.adjust(diff1_wilcox$p.value,"bonferroni")
diff1_wilcox <- diff %>% filter(p.value < 0.05)

##绘图数据获取
#对于左侧的组间丰度均值比较条形图，我们首先根据差异性检验的结果从原始的丰度数据文件中提取具有显著差异的列，之后按照分组计算其组内平均丰度，再转换成ggplot绘图所用的长格式数据框
abun.bar_t.test <- data1[,c(diff$var,"CommunityType")] %>% gather(variable,value,-CommunityType) %>% group_by(variable,CommunityType) %>% summarise(Mean = mean(value))

diff.mean <- diff[,c("var","estimate","p.value","conf.low","conf.high")]
diff.mean$CommunityType <- c(ifelse(diff.mean$estimate >0,levels(data1$CommunityType)[1],
                            levels(data1$CommunityType)[2]))
diff.mean <- diff.mean[order(diff.mean$estimate,decreasing = TRUE),]

library(ggplot2)
cbbPalette <- c("#F28E97", "#8FA9FC")
abun.bar_t.test$variable <- factor(abun.bar_t.test$variable,levels = rev(diff.mean$var))

p1 <- ggplot(abun.bar_t.test,aes(variable,log10(Mean),fill = CommunityType)) +
    scale_x_discrete(limits = levels(diff.mean$var)) +
    coord_flip() +
    xlab("") +
    ylab("Mean abundance(log)") +
    theme(panel.background = element_rect(fill = 'transparent'),
          panel.grid = element_blank(),
          axis.ticks.length = unit(0.4,"lines"),
          axis.ticks = element_line(color='black'),
          axis.line = element_line(colour = "black"),
          axis.title.x=element_text(colour='black', size=12,face = "bold"),
          axis.text=element_text(colour='black',size=10,face = "bold"),
          legend.title=element_blank(),
          legend.text=element_text(size=12,face = "bold",colour = "black"),
          legend.position = c(-1,-0.1),
          legend.direction = "horizontal",
          legend.key.width = unit(0.8,"cm"),
          legend.key.height = unit(0.5,"cm"))
    for (i in 1:(nrow(diff.mean) - 1))
    p1 <- p1 + annotate('rect', xmin = i+0.5, xmax = i+1.5, ymin = -Inf, ymax = Inf,
                        fill = ifelse(i %% 2 == 0, 'white', 'gray95'))
 
p1 <- p1 +
    geom_bar(stat = "identity",position = "dodge",width = 0.7,colour = "black") +
    scale_fill_manual(values=cbbPalette)

##右侧散点图
diff.mean$var <- factor(diff.mean$var,levels = levels(abun.bar_t.test$variable))
diff.mean$p.value <- signif(diff.mean$p.value,3)
diff.mean$p.value <- as.character(diff.mean$p.value)

p2 <- ggplot(diff.mean,aes(var,estimate,fill = CommunityType)) +
    theme(panel.background = element_rect(fill = 'transparent'),
          panel.grid = element_blank(),
          axis.ticks.length = unit(0.4,"lines"),
          axis.ticks = element_line(color='black'),
          axis.line = element_line(colour = "black"),
          axis.title.x=element_text(colour='black', size=12,face = "bold"),
          axis.text=element_text(colour='black',size=10,face = "bold"),
          axis.text.y = element_blank(),
          legend.position = "none",
          axis.line.y = element_blank(),
          axis.ticks.y = element_blank(),
          plot.title = element_text(size = 15,face = "bold",colour = "black",hjust = 0.5)) +
    scale_x_discrete(limits = levels(diff.mean$var)) +
    coord_flip() +
    xlab("") +
    ylab("Difference in mean abundance") +
    labs(title="95% confidence intervals")
 
for (i in 1:(nrow(diff.mean) - 1))
    p2 <- p2 + annotate('rect', xmin = i+0.5, xmax = i+1.5, ymin = -Inf, ymax = Inf,
                        fill = ifelse(i %% 2 == 0, 'white', 'gray95'))
 
p2 <- p2 +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high),
                  position = position_dodge(0.8), width = 0.5, size = 0.5) +
    geom_point(shape = 21,size = 3) +
    scale_fill_manual(values=cbbPalette) +
    geom_hline(aes(yintercept = 0), linetype = 'dashed', color = 'black')

p3 <- ggplot(diff.mean,aes(var,estimate,fill = CommunityType)) +
    geom_text(aes(y = 0,x = var),label = diff.mean$p.value,
              hjust = 0,fontface = "bold",inherit.aes = FALSE,size = 3) +
    geom_text(aes(x = nrow(diff.mean)/2 +0.5,y = 0.85),label = "P-value (corrected)",
             srt = 90,fontface = "bold",size = 5) +
    coord_flip() +
    ylim(c(0,1)) +
    theme(panel.background = element_blank(),
          panel.grid = element_blank(),
          axis.line = element_blank(),
          axis.ticks = element_blank(),
          axis.text = element_blank(),
          axis.title = element_blank())

library(patchwork)
p <- p1 + p2 +p3 + plot_layout(widths = c(4,6,2))
ggsave("D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Figure//Figure2C_1_Pathway_stamp_all_20250113.pdf",p1,width = 6,height = 4)
ggsave("D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Figure//Figure2C_1_Pathway_stamp_all_20250113_2.pdf",p2,width = 6,height = 4)

#ggsave("D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Figure//Figure2C_1_Pathway_stamp_all_20240416.pdf",p1,width = 6,height = 4)
#ggsave("D://LCW//BQ_CRS//merged_3batch//Figure20250107_github//Figure//Figure2C_2_Pathway_stamp_all_20240416.pdf",p2,width = 4,height = 4)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
